name: tracker
description: "A new Flutter project."
version: 0.0.1+0
publish_to: "none"

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  location: ^5.0.3
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
